[package]
name = "bevy-asteroids"
version = "0.1.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { path = "/home/boris/work/rust/forks/bevy" }
rand = "0.7.3"
