[package]
name = "kataster"
version = "0.3.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

[dependencies]
#bevy = { git = "https://github.com/bevyengine/bevy" }
#bevy = { path = "/home/boris/work/gits/bevy"}
bevy = "0.3.0"
rand = "0.7.3"
#bevy_rapier2d = { path = "/home/boris/work/gits/bevy_rapier/bevy_rapier2d" }
bevy_rapier2d = "0.6.2"


# Ensure crates reference the same versions
# or customize a sub-crate version
#[patch.crates-io]
#bevy = { path = "/home/boris/work/gits/bevy"}
#bevy= {git="https://github.com/bevyengine/bevy"}
